Repository pimcore/personalization-bundle, pull requests merged in 2023-04, with the labels that each got.

#6 Remove leftover file
  tests/Unit.suite.yml~
Labels: bug

#4 [Task] : Remove class alias
  src/Model/Tool/Targeting/TargetGroup.php
Labels: Task

#1 [Task] Adapted yaml changes from main ticket
  config/services.yaml
  config/targeting.yaml
  config/targeting/listeners.yaml
  config/targeting/services.yaml
Labels: enhancement

#8 Adapt Master to Main changes
  src/Targeting/ConditionFactory.php
  src/Targeting/EventListener/Frontend/FullPageCacheCookieCleanupListener.php
  src/Targeting/Storage/CookieStorage.php
  src/Targeting/Storage/RedisStorage.php
  src/Targeting/Storage/SessionStorage.php
Labels: Task

#9 [Task]: re-add `lcobucci\jwt` package requirement
  composer.json
Labels: Task

#12 Adapt newsletter changes
  .github/ci/files/config/config.yaml
  .github/ci/files/config/system.yml
Labels: Task

#23 Readd required packages
  composer.json
  config/services.yaml
  src/Document/Newsletter/AddressSourceAdapter/DefaultAdapter.php
Labels: Task

#25 Setup php-cs fixer
  .github/workflows/php-cs-fixer.yaml
  .gitignore
  .php-cs-fixer.dist.php
  .php_cs.dist
Labels: Task

#26 Setup Codeception
  .github/ci/files/config/bundles.php
  .github/ci/files/config/system.yml
  .github/workflows/codeception.yaml
  composer.json
  tests/Support/Helper/Unit.php
  tests/Unit.suite.yml
Labels: Task

#24 Setup php stan
  .github/workflows/static-analysis.yaml
  composer.json
  phpstan-baseline.neon
  phpstan-bootstrap.php
  phpstan.neon
  src/DependencyInjection/Configuration.php
  src/Targeting/ConditionMatcher.php
Labels: Task

#27 Setup PO editor sync
  .github/workflows/poeditor-export.yaml
Labels: Task

#28 Adapt new admin bundle changes
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  composer.json
  src/Controller/Admin/TargetingController.php
  src/PimcorePersonalizationBundle.php
  src/Targeting/Document/DocumentTargetingConfigurator.php
Labels: Task

#30 Add bundle specific css to personalization bundle
  public/css/icons.css
Labels: Bug

#31 [Docs] Add an installation guide for Personalization Bundle
  doc/Installation.md
Labels: Task

#32 [Docs] add link to installation page
  README.md
Labels: Task
