Repository pimcore/personalization-bundle, pull requests merged in 2024-04, with the labels that each got.

#71 Update CLA check
  .github/workflows/cla.yml
Labels: Task

#72 Bump lcobucci/jwt to version 5 (#11)
  composer.json
  src/Targeting/Storage/Cookie/JWTCookieSaveHandler.php
Labels: Pimcore:ToDo

#73 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo
